language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install pytest
  - pip install coveralls

# command to run tests
script:
  - python -m coverage run -p -m py.test tests/test1
  - python -m coverage run -p -m py.test tests/test_nested
  - python -m coverage run -p -m py.test tests/test_exceptions

after_success: coveralls