language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install pytest

# command to run tests
script:
  - python -m pytest tests/test1
  - python -m pytest tests/test_nested
  - python -m pytest tests/test_exceptions

after_success: coveralls